# This example intended as baseline to use k3d for the deployment of GitLab
# - Minimized CPU/Memory load, can fit into 3 CPU, 6 GB of RAM (barely)
# - Services that are not compatible with how Minikube runs are disabled
# - Some services entirely removed, or scaled down to 1 replica.
# - Configured to use gitlab.local for the domain
# 
# From official Gitlab doc: 
#   https://docs.gitlab.com/charts/development/minikube/#deploying-gitlab-with-minimal-settings
#   https://gitlab.com/gitlab-org/charts/gitlab/blob/master/examples/values-minikube-minimum.yaml


global:
  ingress:
    enabled: false
    configureCertmanager: false
    class: "nginx"
  hosts:
    domain: localhost
    https: false
  rails:
    bootsnap:
      enabled: false
  shell:
    port: 32022

installCertmanager: false
nginx-ingress:
  enabled: false
prometheus:
  install: false
gitlab-runner:
  install: false
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    service:
      type: NodePort
      nodePort: 32022
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
